default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  host:     <%= ENV['PG_HOST'] %>
  port:     <%= ENV['PG_PORT'] %>
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rd_cat_challenge_development

test:
  <<: *default
  database: rd_cat_challenge_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
