:concurrency: 5
:queues:
  - default
  - mailers

:cron:
  cleanup_abandoned_carts:
    class: 'Carts::CleanupJob'
    cron: '*/30 * * * *'
    description: 'Remove abandoned carts and discard old ones'
